### ISSUE TITLE
Rule doesn't work for license file with name LICENSE 

### ISSUE THREAD

**Issue by Caraczan** [braver/FileIcons#56]
I think it would be good idea to add icon to file for license. 

![image](https://user-images.githubusercontent.com/45484392/217675818-806d7c6b-d582-4256-8867-d4012c992ca8.png)

This is icon from gitlab. I don't know if this icon is copyrighted but it is good looking in my opinion.

Maybe it can help.

**Comment by braver** [comment]
Licenses are just plain text files. There are no packages in package control that make syntaxes specifically for licenses. There are also no recognizable characteristics of these files to make a syntax work for them automatically. Therefore it's impossible to make specific icons for them (as far as I know).

**Comment by jwortmann** [comment]
@braver You already have an icon for license files in this package: https://github.com/braver/FileIcons/blob/master/theme/file_type_license.png, and also the corresponding preferences file: https://github.com/braver/FileIcons/blob/master/preferences/file_type_license.tmPreferences

The only missing part is, that it's not applied due to the missing syntax. You could add one into the https://github.com/braver/FileIcons/tree/master/syntaxes folder, like this:
```yaml
%YAML 1.2
---
# https://www.sublimetext.com/docs/syntax.html
name: Plain Text (License)
file_extensions:
  - LICENSE
scope: text.plain.license
hidden: true

contexts:
  main:
    - include: scope:text.plain#prototype
    - include: scope:text.plain
```

And possibly another one for files named `LICENSE.md`, by adjusting `file_extensions` to `- LICENSE.md` and deriving from the Markdown syntax.
